on: push

env:
  DENO_VERSION: 1.24.1
  TARGETS: |
    x86_64-unknown-linux-gnu
    x86_64-pc-windows-msvc
    x86_64-apple-darwin
    aarch64-apple-darwin

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - run: deno test --lock=lock.json --allow-read --allow-env --allow-net
        env:
          GRANFALLOON_TOKEN: ${{ github.token }}

      - run: 'echo "$TARGETS"
              | xargs -i deno compile
                           --allow-read
                           --allow-net
                           --allow-env
                           --target="{}"
                           --output="dist/granfalloon-{}"
                           --lock=lock.json
                           src/mod.js'

      - run: deno bundle --lock=lock.json src/mod.js -- dist/granfalloon.js

      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: dist/*
